// Package main provides a build tool for Hugo blogs with D2 diagram support and resume PDF generation.
//
// # Overview
//
// This tool automatically:
//   - Renders D2 diagram files (.d2) to SVG format for use in Hugo sites
//   - Generates a PDF version of your resume from content/resume/index.md
//
// It integrates with Hugo's build and development workflow to provide live reloading of diagrams.
//
// # D2 Integration
//
// D2 (https://d2lang.com) is a declarative diagram language. This tool:
//   - Finds all .d2 files in the Hugo content directory
//   - Renders them to .svg files in the same location
//   - Reads rendering options from Hugo's config.toml [params.d2] section
//   - Watches for changes and re-renders automatically in development mode
//
// # Assumptions
//
//   - The d2 command-line tool is installed and available in PATH
//   - Chrome/Chromium browser is installed (for PDF generation)
//   - Hugo content lives in a 'content/' directory
//   - Hugo config is in 'config.toml' at the project root
//   - Generated .svg files and resume.pdf are git-ignored (only sources are committed)
//   - D2 files use the Hugo shortcode: {{< d2 src="diagram.d2" >}}
//   - Resume content is at content/resume/index.md
//
// # Usage
//
//	# Render all D2 files and generate resume PDF (for production builds)
//	go run blog.go
//
//	# Development mode: start Hugo server with D2 watching
//	go run blog.go --serve
//
//	# Watch D2 files only (without Hugo server)
//	go run blog.go --watch
//
//	# Show detailed rendering output
//	go run blog.go --verbose
//
// # Resume PDF Generation
//
// The tool automatically generates a PDF from content/resume/index.md:
//   - Watches public/resume/index.html (generated by Hugo)
//   - Uses headless Chrome to render the HTML file with your theme's styling
//   - Saves the PDF to public/resume.pdf (served at /resume.pdf)
//   - Regenerates automatically when the resume HTML changes
//   - PDF preserves text as searchable text (ATS-compatible)
//   - public/ directory is git-ignored, including the generated PDF
//
// Build workflow:
//  1. go run blog.go          # Renders D2 files
//  2. hugo --gc --minify      # Builds site including resume HTML
//  3. go run blog.go          # Generates PDF from built HTML
//
// # Configuration
//
// D2 rendering options are read from config.toml:
//
//	[params.d2]
//	    theme = "1"        # D2 theme ID (0-8) or name
//	    layout = "elk"     # Layout engine: elk, dagre, etc.
//	    sketch = false     # Hand-drawn style
//	    pad = 10           # Padding in pixels
//
// # Integration with Hugo
//
// In development (--serve mode):
//  1. Renders all D2 files initially
//  2. Starts Hugo dev server
//  3. Watches for D2 file changes and re-renders
//  4. Hugo detects SVG changes and triggers browser reload
//
// In production (CI/CD):
//  1. Run 'go run blog.go' to render all diagrams
//  2. Run 'hugo' to build the site with the generated SVGs
//
// # File Watching
//
// The tool watches:
//   - All .d2 files in content/ → re-renders individual file on change
//   - config.toml → re-renders ALL diagrams if D2 config changes
//   - New directories created in content/ → automatically adds to watch list
//
// Changes are debounced (300ms) to avoid multiple renders during rapid edits.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/BurntSushi/toml"
	"github.com/fsnotify/fsnotify"
)

// errPDFSourceMissing is returned by generatePDF when the (Hugo-rendered)
// markdown source file doesn't exist yet. Callers use errors.Is to
// distinguish this expected pre-build state from genuine failures
// (pandoc missing, render errors).
var errPDFSourceMissing = errors.New("markdown source not found")

const (
	// Defaults for --pdf-only when no overrides are supplied. The source
	// is Hugo's resolved markdown output (see layouts/_default/single.md
	// and the `markdown` output format in config.toml), NOT the raw
	// content file — Hugo has already turned {{< ref >}} shortcodes into
	// real URLs by the time we get here.
	defaultPDFSrc = "public/resume/index.md"
	defaultPDFOut = "public/resume.pdf"
)

// Config represents the Hugo config.toml structure containing D2 rendering settings.
// Only the [params.d2] section is parsed; other Hugo settings are ignored.
type Config struct {
	Params struct {
		D2 struct {
			Theme  string `toml:"theme"`  // D2 theme ID or name (e.g., "1", "cool-classics")
			Layout string `toml:"layout"` // Layout engine (e.g., "elk", "dagre")
			Sketch bool   `toml:"sketch"` // Enable hand-drawn sketch style
			Pad    int    `toml:"pad"`    // Padding in pixels around diagrams
		} `toml:"d2"`
	} `toml:"params"`
}

// getDefaultBaseURL returns the appropriate base URL for the current environment.
// In GitHub Codespaces, it constructs the forwarded URL. Otherwise, it returns localhost.
func getDefaultBaseURL() string {
	if codespace := os.Getenv("CODESPACE_NAME"); codespace != "" {
		// GitHub Codespaces environment detected
		return fmt.Sprintf("https://%s-1313.app.github.dev", codespace)
	}
	return "http://localhost:1313"
}

func main() {
	// Define flags
	serve := flag.Bool("serve", false, "Run Hugo dev server with D2 watching")
	watch := flag.Bool("watch", false, "Watch D2 files only (no Hugo server)")
	verbose := flag.Bool("verbose", false, "Show detailed output")
	pdfOnly := flag.Bool("pdf-only", false, "Generate a PDF from a Hugo markdown source and exit")
	pdfSrc := flag.String("pdf-src", defaultPDFSrc, "Markdown source for --pdf-only")
	pdfOut := flag.String("pdf-out", defaultPDFOut, "Output path for --pdf-only")
	baseURL := flag.String("baseURL", "", "Base URL for Hugo server (auto-detects Codespaces if empty)")
	flag.Parse()

	// --pdf-only: generate one PDF and exit. Used by `task build` and CI.
	// Defaults to the resume but accepts arbitrary --pdf-src/--pdf-out so
	// any page in the site can be exported the same way.
	if *pdfOnly {
		if err := generatePDF(*pdfSrc, *pdfOut, *verbose); err != nil {
			log.Fatalf("Failed to generate PDF: %v", err)
		}
		return
	}

	// Resolve baseURL with auto-detection
	if *baseURL == "" {
		*baseURL = getDefaultBaseURL()
	}

	// Ensure d2 is installed
	if !commandExists("d2") {
		log.Fatal("d2 is not installed. Install: curl -fsSL https://d2lang.com/install.sh | sh -s --")
	}

	// pandoc + xelatex are required for PDF generation. Warn (don't fatal)
	// so D2-only workflows still run when neither is installed. blog.go
	// can also fall back to `docker run pandoc/extra` when Docker is
	// available — CI relies on that fallback.
	switch {
	case commandExists("pandoc"):
		if *verbose {
			log.Println("Found pandoc — will use native install for PDF generation")
		}
	case commandExists("docker"):
		if *verbose {
			log.Println("pandoc not in PATH — will use `docker run pandoc/extra` for PDF generation")
		}
	default:
		log.Println("Warning: neither pandoc nor docker found — resume PDF generation will fail.")
		log.Println("  macOS: brew install pandoc && brew install --cask mactex-no-gui")
		log.Println("  Linux: apt-get install pandoc texlive-xetex texlive-fonts-extra")
	}

	// Load Hugo config to get D2 settings
	config := loadConfig("config.toml")

	// Render all D2 files initially (idempotent — skips up-to-date SVGs)
	if err := renderAll("content", config, *verbose, false); err != nil {
		log.Fatalf("Failed to render D2 files: %v", err)
	}

	// Eagerly regenerate the resume PDF on every startup (build OR serve)
	// so the page that the dev server is about to display already has a
	// fresh /resume.pdf to download. The markdown watcher handles
	// subsequent re-gens for in-session edits.
	if err := generatePDF(defaultPDFSrc, defaultPDFOut, *verbose); err != nil {
		if errors.Is(err, errPDFSourceMissing) {
			if *verbose {
				log.Printf("Note: %v", err)
			}
		} else {
			log.Printf("Warning: %v", err)
		}
	}

	// Start appropriate mode
	switch {
	case *serve:
		runServeMode("content", "config.toml", config, *verbose, *baseURL)
	case *watch:
		runWatchMode("content", "config.toml", config, *verbose)
	}
}

// commandExists checks if a command is available in the system PATH.
func commandExists(cmd string) bool {
	_, err := exec.LookPath(cmd)
	return err == nil
}

// Hugo is the source of truth for permalink resolution. We rely on a
// `markdown` output format (configured in config.toml; layout in
// layouts/_default/single.md) to write the page as plain markdown with
// {{< ref >}} shortcodes resolved via .RenderShortcodes. blog.go just
// reads that file and pipes it to pandoc — no regex permalink
// reconstruction in Go.

// loadConfig reads Hugo's config.toml and extracts D2 rendering settings.
// Returns an empty config (with safe defaults) if the file cannot be read.
// This allows the tool to run even without explicit D2 configuration.
func loadConfig(path string) *Config {
	var cfg Config
	if _, err := toml.DecodeFile(path, &cfg); err != nil {
		log.Printf("Warning: Could not load %s: %v", path, err)
	}
	return &cfg
}

// buildD2Command constructs a d2 command with rendering options from config.
//
// The command will render d2File to an SVG with the same basename.
// For example: "diagram.d2" → "diagram.svg"
//
// D2 options are applied in this order:
//   - --theme (if specified in config)
//   - --layout (if specified in config)
//   - --sketch (if enabled in config)
//   - --pad (if > 0 in config)
func buildD2Command(d2File string, config *Config) *exec.Cmd {
	args := []string{}

	// Add D2 options from config
	if theme := config.Params.D2.Theme; theme != "" {
		args = append(args, "--theme="+theme)
	}
	if layout := config.Params.D2.Layout; layout != "" {
		args = append(args, "--layout="+layout)
	}
	if config.Params.D2.Sketch {
		args = append(args, "--sketch")
	}
	if pad := config.Params.D2.Pad; pad > 0 {
		args = append(args, fmt.Sprintf("--pad=%d", pad))
	}

	// Add input and output files
	svgFile := strings.TrimSuffix(d2File, ".d2") + ".svg"
	args = append(args, d2File, svgFile)

	return exec.Command("d2", args...)
}

// renderFile renders a single D2 diagram file to SVG format.
//
// The SVG is written to the same directory with a .svg extension.
// Example: content/blog/2025-01-01/diagram.d2 → diagram.svg
//
// Returns an error if the d2 command fails. The error includes both
// the error message and any output from d2 for debugging.
func renderFile(d2File string, config *Config, verbose bool) error {
	if verbose {
		log.Printf("Rendering %s", d2File)
	} else {
		log.Printf("Rendering %s", filepath.Base(d2File))
	}

	cmd := buildD2Command(d2File, config)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%s: %v\n%s", d2File, err, output)
	}

	return nil
}

// renderAll finds and renders D2 files in the content directory. By default
// it skips files whose .svg is already newer than the .d2 source (and newer
// than config.toml), making repeat invocations cheap — important because the
// Taskfile's render-d2 dep and `go run blog.go --serve` both call this.
//
// Files are rendered concurrently for performance. Any errors are collected
// and reported after all renders complete. Returns an error if any renders fail.
//
// Pass force=true to re-render every file regardless of mtime. Used when
// config.toml changes during a running session, since options like theme
// affect output without changing any .d2 source.
func renderAll(contentDir string, config *Config, verbose, force bool) error {
	d2Files, err := findD2Files(contentDir)
	if err != nil {
		return err
	}

	if len(d2Files) == 0 {
		log.Println("No .d2 files found")
		return nil
	}

	var configMTime time.Time
	if cfgInfo, err := os.Stat("config.toml"); err == nil {
		configMTime = cfgInfo.ModTime()
	}

	var stale []string
	if force {
		stale = d2Files
	} else {
		for _, f := range d2Files {
			if isStale(f, configMTime) {
				stale = append(stale, f)
			}
		}
	}

	if len(stale) == 0 {
		if verbose {
			log.Printf("All %d D2 SVG(s) up-to-date", len(d2Files))
		}
		return nil
	}

	log.Printf("Rendering %d of %d D2 file(s)", len(stale), len(d2Files))

	// Render stale files concurrently
	var wg sync.WaitGroup
	errChan := make(chan error, len(stale))

	for _, file := range stale {
		wg.Add(1)
		go func(f string) {
			defer wg.Done()
			if err := renderFile(f, config, verbose); err != nil {
				errChan <- err
			}
		}(file)
	}

	wg.Wait()
	close(errChan)

	// Report errors
	var errCount int
	for err := range errChan {
		log.Printf("ERROR: %v", err)
		errCount++
	}

	if errCount > 0 {
		return fmt.Errorf("%d file(s) failed", errCount)
	}

	log.Println("✓ D2 rendering complete")
	return nil
}

// isStale reports whether a .d2 file's corresponding .svg needs re-rendering.
// True when the SVG is missing, older than the source, or older than
// config.toml (since theme/layout changes affect output).
func isStale(d2File string, configMTime time.Time) bool {
	svgFile := strings.TrimSuffix(d2File, ".d2") + ".svg"
	svgInfo, err := os.Stat(svgFile)
	if err != nil {
		return true
	}
	if !configMTime.IsZero() && svgInfo.ModTime().Before(configMTime) {
		return true
	}
	d2Info, err := os.Stat(d2File)
	if err != nil {
		return true
	}
	return svgInfo.ModTime().Before(d2Info.ModTime())
}

// findD2Files recursively walks a directory tree and returns all .d2 file paths.
func findD2Files(dir string) ([]string, error) {
	var files []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".d2") {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

// regenPDFSubprocess invokes `go run blog.go --pdf-only` as a child process.
//
// The dev-mode watcher uses this instead of calling generatePDF() directly
// so that edits to blog.go during a `task` session take effect without
// restarting the dev server. `go run` recompiles the source each call, so
// any change to the pandoc args, preamble, or fonts shows up on the next
// markdown save.
func regenPDFSubprocess(srcPath, outPath string, verbose bool) error {
	args := []string{"run", "blog.go", "--pdf-only", "--pdf-src=" + srcPath, "--pdf-out=" + outPath}
	if verbose {
		args = append(args, "--verbose")
	}
	cmd := exec.Command("go", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// generatePDF converts a Hugo-rendered markdown file into a PDF using
// pandoc. The input is the OUTPUT of Hugo's `markdown` output format —
// shortcodes already resolved, ready to feed straight to pandoc.
//
// The pipeline is intentionally generic — any page in the site can be
// exported by enabling the `md` output format on it and passing
// --pdf-src=public/<path>/index.md --pdf-out=public/<name>.pdf.
//
// pandoc resolution order:
//  1. `pandoc` in PATH (native install — used locally on Mac per
//     content/til/2026/04/15/markdown-to-pdf-on-mac/index.md)
//  2. `docker run pandoc/extra` (used in CI; image includes xelatex
//     and TeX Gyre fonts, ~300MB single pull per runner)
//
// Flags match the markdown-to-pdf-on-mac TIL: xelatex engine, TeX Gyre
// fonts at 11pt, 1.25" margins, navy links, sans-serif headings.
func generatePDF(srcPath, outPath string, verbose bool) error {
	src, err := os.ReadFile(srcPath)
	if os.IsNotExist(err) {
		return fmt.Errorf("%w at %s (run Hugo first to produce the markdown output)", errPDFSourceMissing, srcPath)
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", srcPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outPath), err)
	}

	if verbose {
		log.Printf("Generating PDF: %s → %s", srcPath, outPath)
	} else {
		log.Printf("Generating PDF: %s", outPath)
	}

	if err := invokePandoc(string(src), outPath, verbose); err != nil {
		return err
	}

	log.Printf("✓ PDF generated: %s", outPath)
	return nil
}

// pandocArgs builds the pandoc flag set for PDF generation.
//
// Font selection uses kpathsea-style file specs (the *-regular, *-bold,
// *-italic, *-bolditalic glob pattern), NOT family names like "Latin
// Modern Roman". The family-name approach fails on macOS because
// xelatex queries Core Text — which doesn't index TeX Live's font tree
// — but kpathsea finds them everywhere TeX Live is installed (MacTeX,
// apt texlive on Linux, the pandoc/extra Docker image). One spec, every
// host.
//
// Fonts are the Latin Modern family. Originally we used TeX Gyre per
// content/til/2026/04/15/markdown-to-pdf-on-mac/, but the pandoc/extra
// Docker image (used by CI) ships only Latin Modern by default and
// dropping a tlmgr install step kept CI fast and self-contained.
func pandocArgs(outPath string) []string {
	// Latin Modern uses inconsistent slant/weight suffixes across the
	// Roman/Sans/Mono families: roman has *-italic, sans has *-oblique,
	// mono ships no bold at all. Custom option strings per family
	// instead of one shared pattern.
	const romanOpts = "Extension=.otf, UprightFont=*-regular, BoldFont=*-bold, ItalicFont=*-italic, BoldItalicFont=*-bolditalic"
	const sansOpts = "Extension=.otf, UprightFont=*-regular, BoldFont=*-bold, ItalicFont=*-oblique, BoldItalicFont=*-boldoblique"
	const monoOpts = "Extension=.otf, UprightFont=*-regular, ItalicFont=*-italic"
	return []string{
		"--pdf-engine=xelatex",
		"--from=markdown",
		"-V", "mainfont=lmroman10",
		"-V", "mainfontoptions=" + romanOpts,
		"-V", "sansfont=lmsans10",
		"-V", "sansfontoptions=" + sansOpts,
		"-V", "monofont=lmmono10",
		"-V", "monofontoptions=" + monoOpts,
		"-V", "fontsize=11pt",
		"-V", "geometry:top=0.85in, bottom=0.85in, left=0.85in, right=0.85in",
		"-V", "linestretch=1.15",
		"-V", "colorlinks=true",
		"-V", "urlcolor=[rgb]{0.13,0.33,0.60}",
		"-V", "linkcolor=[rgb]{0.13,0.33,0.60}",
		// Heading hierarchy sized for resume-style hierarchy: name → top
		// section → company → job title. titlesec overrides the article-
		// class defaults so each level is visibly bigger than body text
		// and there's a clear step-down between levels.
		"-V", `header-includes=\usepackage{titlesec} \titleformat{\section}{\Huge\bfseries\sffamily}{}{0em}{} \titleformat{\subsection}{\huge\bfseries\sffamily}{}{0em}{} \titleformat{\subsubsection}{\LARGE\bfseries\sffamily}{}{0em}{} \titleformat{\paragraph}[block]{\Large\bfseries\sffamily}{}{0em}{}`,
		"-o", outPath,
	}
}

// invokePandoc runs pandoc against the preprocessed markdown content,
// writing the PDF to outPath. Prefers a native `pandoc` binary; falls
// back to `docker run pandoc/extra` when only Docker is available.
func invokePandoc(content, outPath string, verbose bool) error {
	args := pandocArgs(outPath)

	if _, err := exec.LookPath("pandoc"); err == nil {
		return runPandoc(exec.Command("pandoc", args...), content, verbose)
	}

	if _, err := exec.LookPath("docker"); err == nil {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getwd: %w", err)
		}
		dockerArgs := []string{
			"run", "--rm", "-i",
			"-v", cwd + ":/data",
			"-w", "/data",
			"pandoc/extra",
		}
		return runPandoc(exec.Command("docker", append(dockerArgs, args...)...), content, verbose)
	}

	return fmt.Errorf("neither 'pandoc' nor 'docker' found in PATH — install pandoc + xelatex (macOS: brew install pandoc && brew install --cask mactex-no-gui; Linux: apt-get install pandoc texlive-xetex texlive-fonts-extra) or install Docker")
}

// runPandoc executes the provided pandoc (or docker-wrapped pandoc)
// command, piping content to its stdin. On failure the captured stderr
// is included in the returned error so callers see pandoc's diagnostic
// output even in non-verbose mode.
func runPandoc(cmd *exec.Cmd, content string, verbose bool) error {
	cmd.Stdin = strings.NewReader(content)
	if verbose {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		return cmd.Run()
	}
	var stderr strings.Builder
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("pandoc failed: %w\n%s", err, stderr.String())
	}
	return nil
}

// watchResumePDF monitors Hugo's rendered resume markdown for changes
// and regenerates public/resume.pdf via pandoc.
//
// In dev mode `hugo server --renderToDisk` writes public/resume/index.md
// (the `markdown` output format) whenever content/resume/index.md is
// edited. fsnotify catches that write and triggers a debounced pandoc
// re-run, so the user always has a fresh /resume.pdf to download.
//
// The watcher runs until ctx is cancelled (Ctrl+C).
func watchResumePDF(ctx context.Context, verbose bool) {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Printf("Warning: Failed to create resume watcher: %v", err)
		return
	}
	defer watcher.Close()

	resumeDir := filepath.Join("public", "resume")

	// Wait for public/resume to exist (Hugo may not have rendered yet).
	for i := 0; i < 30; i++ {
		if _, err := os.Stat(resumeDir); err == nil {
			break
		}
		select {
		case <-ctx.Done():
			return
		case <-time.After(1 * time.Second):
		}
	}

	if err := watcher.Add(resumeDir); err != nil {
		log.Printf("Warning: Failed to watch resume directory: %v", err)
		return
	}

	var debounceTimer *time.Timer
	var debounceMu sync.Mutex

	// Initial gen only if the PDF is stale relative to the markdown.
	// Covers the cold-start race where Hugo wrote the .md before
	// fsnotify attached (we'd otherwise miss the Write event entirely).
	mdPath := filepath.Join(resumeDir, "index.md")
	pdfPath := defaultPDFOut
	if mdInfo, err := os.Stat(mdPath); err == nil {
		pdfInfo, pdfErr := os.Stat(pdfPath)
		if pdfErr != nil || pdfInfo.ModTime().Before(mdInfo.ModTime()) {
			// Initial-gen at dev-server startup: in-process call is
			// fine because blog.go was just compiled. Only the in-loop
			// regen below needs the subprocess hop to pick up future
			// blog.go edits during the session.
			if err := generatePDF(mdPath, pdfPath, verbose); err != nil && !errors.Is(err, errPDFSourceMissing) {
				log.Printf("Warning: Failed to generate resume PDF: %v", err)
			}
		}
	}

	for {
		select {
		case <-ctx.Done():
			return

		case event := <-watcher.Events:
			if event.Name == mdPath && event.Op&(fsnotify.Write|fsnotify.Create) != 0 {
				debounceMu.Lock()
				if debounceTimer != nil {
					debounceTimer.Stop()
				}
				debounceTimer = time.AfterFunc(300*time.Millisecond, func() {
					if err := regenPDFSubprocess(mdPath, pdfPath, verbose); err != nil && !errors.Is(err, errPDFSourceMissing) {
						log.Printf("Warning: Failed to regenerate PDF: %v", err)
					}
				})
				debounceMu.Unlock()
			}

		case err := <-watcher.Errors:
			log.Printf("Resume watcher error: %v", err)
		}
	}
}

// runServeMode runs the Hugo development server with live D2 diagram and resume PDF reloading.
//
// This is the primary development mode. It:
//  1. Starts a background goroutine watching D2 files
//  2. Starts a background goroutine watching resume HTML for PDF regeneration
//  3. Starts Hugo's dev server in the foreground
//  4. Handles Ctrl+C gracefully, shutting down both processes
//
// The D2 watcher, resume watcher, and Hugo server share a context. When the user hits Ctrl+C,
// the context is cancelled, signaling all goroutines to shutdown cleanly.
//
// Hugo automatically detects when SVG files and PDFs change and triggers browser reload.
func runServeMode(contentDir, configFile string, config *Config, verbose bool, baseURL string) {
	if !commandExists("hugo") {
		log.Fatal("hugo is not installed. Install from https://gohugo.io/installation/")
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Handle Ctrl+C gracefully
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)

	// Start D2 watcher in background
	go func() {
		log.Println("Starting D2 file watcher...")
		watchD2Files(ctx, contentDir, configFile, config, verbose)
	}()

	// Start resume PDF watcher in background
	go func() {
		log.Println("Starting resume PDF watcher...")
		watchResumePDF(ctx, verbose)
	}()

	time.Sleep(500 * time.Millisecond) // Let watchers start

	// Start Hugo server
	log.Printf("Starting Hugo dev server at %s", baseURL)
	// --cleanDestinationDir is intentionally omitted: Hugo's dev server uses
	// it to delete files in public/ that aren't in its source set, which
	// (a) wipes out our resume.pdf and (b) removes public/resume/ during
	// rebuilds, invalidating the fsnotify watcher's dir registration. The
	// flag is for production-build hygiene; in serve mode it just breaks
	// the live-reload loop for our generated PDF.
	//
	// --gc is also intentionally omitted: Hugo's "remove unused cache files"
	// step evicts our resources.GetRemote on-disk cache for the GoatCounter
	// API response (used by layouts/partials/popular-data.html) after a few
	// rebuilds, even though the partial still reads it. The eviction forces
	// a refetch on each rebuild, and any non-2xx blip silently empties the
	// Popular section site-wide. Production (CI) still runs `hugo --gc` —
	// CI runners are ephemeral so there's no cache to thrash.
	// --renderToMemory=false: write rendered output to public/ in dev
	// mode (Hugo's server defaults to in-memory). We need files on disk
	// so blog.go's markdown watcher can read public/resume/index.md (the
	// resolved-shortcodes output) and feed it to pandoc for PDF regen.
	hugoCmd := exec.CommandContext(ctx, "hugo", "server", "--bind", "0.0.0.0", "--baseURL", baseURL, "--buildDrafts", "--noHTTPCache", "--disableFastRender", "--renderToMemory=false")
	hugoCmd.Stdout = os.Stdout
	hugoCmd.Stderr = os.Stderr
	hugoCmd.Stdin = os.Stdin

	if err := hugoCmd.Start(); err != nil {
		log.Fatalf("Failed to start Hugo: %v", err)
	}

	// Wait for shutdown signal
	<-sigChan
	log.Println("\nShutting down...")
	cancel()
	time.Sleep(500 * time.Millisecond)

	if hugoCmd.Process != nil {
		hugoCmd.Process.Kill()
	}
	hugoCmd.Wait()
	log.Println("Stopped")
}

// runWatchMode watches D2 files for changes without starting the Hugo server.
//
// This mode is useful when running Hugo separately (e.g., in a different terminal
// or with custom Hugo flags). The watcher will continue until interrupted with Ctrl+C.
func runWatchMode(contentDir, configFile string, config *Config, verbose bool) {
	log.Printf("Watching %s for D2 changes (Ctrl+C to stop)", contentDir)
	watchD2Files(context.Background(), contentDir, configFile, config, verbose)
}

// watchD2Files monitors the filesystem for D2 diagram and config changes.
//
// It watches:
//   - All .d2 files: re-renders the specific file on change (debounced 300ms)
//   - config.toml: re-renders ALL diagrams if [params.d2] settings change
//   - New directories: automatically adds them to the watch list
//
// The watcher runs until ctx is cancelled. In serve mode, cancellation happens
// when the user hits Ctrl+C. In watch mode, it runs indefinitely.
//
// Debouncing prevents excessive re-renders when files are saved multiple times
// rapidly (e.g., by editors that save on every keystroke).
func watchD2Files(ctx context.Context, contentDir, configFile string, config *Config, verbose bool) {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatalf("Failed to create watcher: %v", err)
	}
	defer watcher.Close()

	// Watch config file
	watcher.Add(configFile)

	// Watch all content directories recursively
	filepath.Walk(contentDir, func(path string, info os.FileInfo, err error) error {
		if err == nil && info.IsDir() {
			watcher.Add(path)
		}
		return nil
	})

	// Debouncing: wait 300ms after last change before rendering
	debounce := make(map[string]*time.Timer)
	var debounceMu sync.Mutex

	for {
		select {
		case <-ctx.Done():
			return

		case event := <-watcher.Events:
			// Config changed - re-render everything (force, since D2
			// sources didn't change but theme/layout options may have)
			if event.Name == configFile && event.Op&fsnotify.Write != 0 {
				log.Println("Config changed - re-rendering all")
				config = loadConfig(configFile)
				renderAll(contentDir, config, verbose, true)
				continue
			}

			// D2 file changed - render it (debounced)
			if strings.HasSuffix(event.Name, ".d2") && event.Op&fsnotify.Write != 0 {
				debounceMu.Lock()
				if timer, exists := debounce[event.Name]; exists {
					timer.Stop()
				}
				debounce[event.Name] = time.AfterFunc(300*time.Millisecond, func() {
					renderFile(event.Name, config, verbose)
				})
				debounceMu.Unlock()
			}

			// New directory - watch it
			if event.Op&fsnotify.Create != 0 {
				if info, err := os.Stat(event.Name); err == nil && info.IsDir() {
					watcher.Add(event.Name)
				}
			}

		case err := <-watcher.Errors:
			log.Printf("Watcher error: %v", err)
		}
	}
}
