# https://taskfile.dev

version: '3'

vars:
  DATE:
   sh: date "+%Y-%m-%d"

tasks:
  default:
    desc: Start dev server with D2 diagram watching
    deps: [render-d2]
    cmds:
      - go run blog.go --serve
    interactive: true

  render-d2:
    desc: Render all D2 diagrams to SVG
    cmds:
      - go run blog.go
    sources:
      - content/**/*.d2
      - config.toml
    generates:
      - content/**/*.svg
    method: checksum
  blog:
    desc: Create a new blog post with a title, TITLE="my-post" task blog
    cmds:
     - hugo new blog/{{.DATE}}/$TITLE/index.md
    env:
      TITLE: ""
  today-i-learned:
    desc: Create a new Today I Learned post, TITLE="the title" task til
    aliases: [til]
    cmds:
     - hugo new til/{{.DATE}}/index.md
     - 'sed -i.bak "2s/title.*/title: $TITLE/" content/til/{{.DATE}}/index.md'
     - rm content/til/{{.DATE}}/index.md.bak
    env:
      TITLE: ""

  build:
    desc: Build the site for production
    deps: [render-d2]
    cmds:
      - hugo
