# https://taskfile.dev

version: "3"

vars:
  DATE:
    sh: date "+%Y-%m-%d"

tasks:
  default:
    desc: Start dev server with D2 diagram watching
    deps: [render-d2]
    cmds:
      - go run blog.go --serve {{if .BASE_URL}}--baseURL {{.BASE_URL}}{{end}}
    interactive: true

  render-d2:
    desc: Render all D2 diagrams to SVG
    cmds:
      - go run blog.go
    sources:
      - content/**/*.d2
      - config.toml
    generates:
      - content/**/*.svg
    method: checksum
  blog:
    desc: Create a new blog post with a title, TITLE="my-post" task blog
    cmds:
      - |
        YEAR=$(echo {{.DATE}} | cut -d'-' -f1)
        MONTH=$(echo {{.DATE}} | cut -d'-' -f2)
        DAY=$(echo {{.DATE}} | cut -d'-' -f3)
        hugo new blog/${YEAR}/${MONTH}/${DAY}/$TITLE/index.md
    env:
      TITLE: ""
  today-i-learned:
    desc: Create a new Today I Learned post, TITLE="my-post" task til
    aliases: [til]
    cmds:
      - |
        YEAR=$(echo {{.DATE}} | cut -d'-' -f1)
        MONTH=$(echo {{.DATE}} | cut -d'-' -f2)
        DAY=$(echo {{.DATE}} | cut -d'-' -f3)
        hugo new til/${YEAR}/${MONTH}/${DAY}/$TITLE/index.md
    env:
      TITLE: ""

  recipe:
    desc: Create a new recipe, TITLE="my-recipe" task recipe
    cmds:
      - hugo new recipes/$TITLE/index.md
    env:
      TITLE: ""

  build:
    desc: Build the site for production
    deps: [render-d2]
    cmds:
      - hugo --gc --minify
      - go run blog.go # Generate resume PDF from built HTML
